name:                 complexity
version:              0.1.0.0
visibility:           public
id:                   complexity-0.1.0.0-4lgIK7IPSldKpe7wqCIGHj
key:                  complexity-0.1.0.0-4lgIK7IPSldKpe7wqCIGHj
license:              BSD-3-Clause
copyright:            2025 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/complexity#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/complexity#readme>

abi:                  5767f635fc83e771a40137341eafad9e
exposed:              True
exposed-modules:
    Complexity GlossAnimation HubbleExpansion InitialGalaxies Lib
    ScaleFactors

hidden-modules:       Paths_complexity
import-dirs:
    /home/alecf/programming_fun/Haskell/complexity/.stack-work/install/x86_64-linux/636017251163959a1564e271613da6127d2673015edf2cdeb1c7d827e0c9ef80/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/complexity-0.1.0.0-4lgIK7IPSldKpe7wqCIGHj

library-dirs:
    /home/alecf/programming_fun/Haskell/complexity/.stack-work/install/x86_64-linux/636017251163959a1564e271613da6127d2673015edf2cdeb1c7d827e0c9ef80/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/complexity-0.1.0.0-4lgIK7IPSldKpe7wqCIGHj

library-dirs-static:
    /home/alecf/programming_fun/Haskell/complexity/.stack-work/install/x86_64-linux/636017251163959a1564e271613da6127d2673015edf2cdeb1c7d827e0c9ef80/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/complexity-0.1.0.0-4lgIK7IPSldKpe7wqCIGHj

dynamic-library-dirs:
    /home/alecf/programming_fun/Haskell/complexity/.stack-work/install/x86_64-linux/636017251163959a1564e271613da6127d2673015edf2cdeb1c7d827e0c9ef80/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3

data-dir:
    /home/alecf/programming_fun/Haskell/complexity/.stack-work/install/x86_64-linux/636017251163959a1564e271613da6127d2673015edf2cdeb1c7d827e0c9ef80/9.10.3/share/x86_64-linux-ghc-9.10.3-b4c3/complexity-0.1.0.0

hs-libraries:         HScomplexity-0.1.0.0-4lgIK7IPSldKpe7wqCIGHj
depends:
    base-4.20.2.0-f074 gloss-1.13.2.2-Bf6ZCtX7s7iD1GIf6vfB1L
    random-1.2.1.3-G0YFm4ccB5AFuGOgLq8SvP
    vector-0.13.2.0-FaXZa7tlyrt4essUrBNbjt

haddock-interfaces:
    /home/alecf/programming_fun/Haskell/complexity/.stack-work/install/x86_64-linux/636017251163959a1564e271613da6127d2673015edf2cdeb1c7d827e0c9ef80/9.10.3/doc/complexity-0.1.0.0/complexity.haddock

haddock-html:
    /home/alecf/programming_fun/Haskell/complexity/.stack-work/install/x86_64-linux/636017251163959a1564e271613da6127d2673015edf2cdeb1c7d827e0c9ef80/9.10.3/doc/complexity-0.1.0.0
