name:                 cosmic-expansion
version:              0.1.0.0
visibility:           public
id:                   cosmic-expansion-0.1.0.0-9HlxaTUQXtH2sDXoZsSSam
key:                  cosmic-expansion-0.1.0.0-9HlxaTUQXtH2sDXoZsSSam
license:              BSD-3-Clause
copyright:            2025 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:
    https://github.com/karakuri-strategist/cosmic-expansion#readme

description:
    Please see the README on GitHub at <https://github.com/githubuser/complexity#readme>

abi:                  5a04522b7cb6ddcb797850d0f0e32d80
exposed:              True
exposed-modules:
    Complexity GlossAnimation GlossConfig HubbleExpansion
    InitialGalaxies NearestNeighbors PhysicsConfig ScaleFactors Vec

hidden-modules:       Paths_cosmic_expansion
import-dirs:
    /home/alecf/programming_fun/Haskell/cosmic-expansion/cosmic-expansion-haskell/.stack-work/install/x86_64-linux/27d58335a6d633641144ccd64e42ccb04b970d8ec0454828ceb4ad90bd055c68/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/cosmic-expansion-0.1.0.0-9HlxaTUQXtH2sDXoZsSSam

library-dirs:
    /home/alecf/programming_fun/Haskell/cosmic-expansion/cosmic-expansion-haskell/.stack-work/install/x86_64-linux/27d58335a6d633641144ccd64e42ccb04b970d8ec0454828ceb4ad90bd055c68/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/cosmic-expansion-0.1.0.0-9HlxaTUQXtH2sDXoZsSSam

library-dirs-static:
    /home/alecf/programming_fun/Haskell/cosmic-expansion/cosmic-expansion-haskell/.stack-work/install/x86_64-linux/27d58335a6d633641144ccd64e42ccb04b970d8ec0454828ceb4ad90bd055c68/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3/cosmic-expansion-0.1.0.0-9HlxaTUQXtH2sDXoZsSSam

dynamic-library-dirs:
    /home/alecf/programming_fun/Haskell/cosmic-expansion/cosmic-expansion-haskell/.stack-work/install/x86_64-linux/27d58335a6d633641144ccd64e42ccb04b970d8ec0454828ceb4ad90bd055c68/9.10.3/lib/x86_64-linux-ghc-9.10.3-b4c3

data-dir:
    /home/alecf/programming_fun/Haskell/cosmic-expansion/cosmic-expansion-haskell/.stack-work/install/x86_64-linux/27d58335a6d633641144ccd64e42ccb04b970d8ec0454828ceb4ad90bd055c68/9.10.3/share/x86_64-linux-ghc-9.10.3-b4c3/cosmic-expansion-0.1.0.0

hs-libraries:         HScosmic-expansion-0.1.0.0-9HlxaTUQXtH2sDXoZsSSam
depends:
    base-4.20.2.0-f074 gloss-1.13.2.2-Bf6ZCtX7s7iD1GIf6vfB1L
    random-1.2.1.3-G0YFm4ccB5AFuGOgLq8SvP
    vector-0.13.2.0-FaXZa7tlyrt4essUrBNbjt

haddock-interfaces:
    /home/alecf/programming_fun/Haskell/cosmic-expansion/cosmic-expansion-haskell/.stack-work/install/x86_64-linux/27d58335a6d633641144ccd64e42ccb04b970d8ec0454828ceb4ad90bd055c68/9.10.3/doc/cosmic-expansion-0.1.0.0/cosmic-expansion.haddock

haddock-html:
    /home/alecf/programming_fun/Haskell/cosmic-expansion/cosmic-expansion-haskell/.stack-work/install/x86_64-linux/27d58335a6d633641144ccd64e42ccb04b970d8ec0454828ceb4ad90bd055c68/9.10.3/doc/cosmic-expansion-0.1.0.0
